### ISSUE TITLE
Instructions setup

### ISSUE THREAD

**Issue by AleksandarFaraj** [bfaliszek/Python-HPMA115S0#1]
Hey, 

Is there have some pictures of how to set up the cables from the sensor to the Raspberry Pie?

**Comment by bfaliszek** [comment]
Sensor Pin 2 (Power input of 5V) = GPIO Pin 4
Sensor Pin 6 (UART TX)=GPIO Pin 10
Sensor Pin 7 (UART RX)=GPIO Pin 8
Sensor Pin 8 (Power Ground Terminal)=GPIO Pin 6

![connection](https://user-images.githubusercontent.com/1752244/34208160-a6b6da52-e58d-11e7-82d0-2b78a602dec8.jpg)

Also disable bluetooth and make sure you have UART enabled. You can check this by typing "sudo raspi-config" in the terminal and selecting "Interfacing options" and then "Serial”.

**Comment by AleksandarFaraj** [comment]
Oh thank you! So amazing! Cheers! 

I'm getting mine in two-three days I believe, hopefully this helps! It will be my first time using hardware, all will be good!

**Comment by AleksandarFaraj** [comment]
Great, just received mine. My cable however has two picoblade heads. How do I buy your cable and whats the name of it?

**Comment by AleksandarFaraj** [comment]
In the image, it looks like Sensor Pin 7 (UART RX) is connected to GPIO Pin 10? I guess the image is not correct?

**Comment by bfaliszek** [comment]
@AleksandarFaraj I am sorry for not responding so long. It is possible that the photo is older than the final configuration. More important is what I wrote above:
Sensor Pin 2 (Power input of 5V) = GPIO Pin 4
Sensor Pin 6 (UART TX)=GPIO Pin 10
Sensor Pin 7 (UART RX)=GPIO Pin 8
Sensor Pin 8 (Power Ground Terminal)=GPIO Pin 6

**Comment by AleksandarFaraj** [comment]
Thank you, we brute forced it :D

**Comment by apanagar** [comment]
Hi - What cable did you buy to connect the picoblade to the raspberry pi? Thanks for the info and pics

**Comment by bfaliszek** [comment]
I use such as these: P8 version https://www.aliexpress.com/item/10Pcs-XH-1-25-28AWG-JST-Double-Electronic-Wire-Connectors-2-3-4-5-6-7/32860186022.html. The cables from the PMS5003 / PMS7003 sensors fit into the HPMA115S0.

![img_2774](https://user-images.githubusercontent.com/1752244/48439315-47bcf580-e786-11e8-9a7f-2a78580b8265.jpeg)

**Comment by apanagar** [comment]
Ah, thats how it's wired. Way easier than re-soddering female pins to a 8p picoblade :)
