### ISSUE TITLE
Jumper Cable Question

### ISSUE THREAD

**Issue by MaddieLowe** [bfaliszek/Python-HPMA115S0#3]
Hello, this isn't an issue, it's a very novice question, but I wasn't sure the best place to ask it.

You were so good as to link to the cables which fit into the HPMA sensor, and I was wondering which jumper cables you used to plug into that cable. I'm taking on pretty much the exact same project, and have bought a cable off of Digikey which fits into the sensor perfectly, but my jumper cables are much larger and will not go into the other end of the cable. I'm not sure if I should be looking for jumper cables with a smaller gauge, or a different rectangular cable assembly which is larger on one end.

Thank you!

**Comment by bfaliszek** [comment]
You can always cut off one plug and connect your jumper cables there. You need 4 of the 8 jumper attached to the plug. 

![](https://user-images.githubusercontent.com/1752244/48439315-47bcf580-e786-11e8-9a7f-2a78580b8265.jpeg)

**Comment by MaddieLowe** [comment]
Yes that makes sense, thanks :)
